# CI de Nível 01 - Disparo Manual através de clique e Push na Master
name: 'N1 - Execução Manual'

# gatilhos / triggers - regras de disparo
on:
  workflow_dispatch:
  push:
    branches:
      - master

# tarefas dentro da pipeline = jobs
jobs:
  mocha-tests:
    # máquina onde o job vai rodar
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # clone do projeto para dentro da máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # instalação do Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x # Versão estável e compatível

      # instalação do Yarn globalmente
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências usando o Yarn
      - name: Instalando dependências
        run: yarn install

      # executar os testes Mocha e gerar o relatório Mochawesome
      - name: Executando testes com Mocha
        run: npx mocha "test/Externo/alunos.externo.test.js" --reporter mochawesome --reporter-options reportDir=mochawesome-report,overwrite=true,html=true,json=true

      # Salvar relatórios (Garante o upload da pasta correta mesmo se o teste falhar)
      - name: Salvando relatórios de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }} # Executa mesmo que algum teste falhe
        with:
          name: Relatório de Testes Mochawesome
          path: ./mochawesome-report